# Generated by Django 2.0.5 on 2018-07-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='visual',
            field=models.ImageField(default='james.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
