# Generated by Django 2.0.5 on 2018-08-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0003_auto_20180730_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksamples',
            old_name='skills',
            new_name='accomplishments',
        ),
        migrations.RenameField(
            model_name='worksamples',
            old_name='snipet_description',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='worksamples',
            old_name='visual',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='worksamples',
            old_name='title',
            new_name='prject_name',
        ),
        migrations.RenameField(
            model_name='worksamples',
            old_name='full_description',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='worksamples',
            name='image3',
            field=models.ImageField(default='b.jpg', upload_to='work_samples/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='image4',
            field=models.ImageField(default='b.jpg', upload_to='work_samples/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='main_image',
            field=models.ImageField(default='b.jpg', upload_to='work_samples/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='objective',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
    ]
