# Generated by Django 2.0.5 on 2018-08-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0004_auto_20180803_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksamples',
            old_name='category',
            new_name='category1',
        ),
        migrations.AddField(
            model_name='worksamples',
            name='category2',
            field=models.CharField(default='sample1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='category3',
            field=models.CharField(default='sample2', max_length=200),
            preserve_default=False,
        ),
    ]
