# Generated by Django 2.0.5 on 2018-08-03 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0005_auto_20180803_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksamples',
            old_name='prject_name',
            new_name='project_name',
        ),
    ]
