# Generated by Django 2.0.5 on 2018-08-03 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0006_auto_20180803_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='alt',
            field=models.CharField(default='A python program I wrote', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='technology_used',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
    ]
