# Generated by Django 2.0.5 on 2018-08-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0007_auto_20180803_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksamples',
            old_name='alt',
            new_name='after_thought',
        ),
        migrations.RemoveField(
            model_name='worksamples',
            name='summary',
        ),
        migrations.AddField(
            model_name='worksamples',
            name='alt_image2',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='alt_image3',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='alt_image4',
            field=models.CharField(default='4', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='alt_main_image',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='challenges',
            field=models.TextField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worksamples',
            name='project_name',
            field=models.CharField(max_length=200),
        ),
    ]
