# Generated by Django 2.0.5 on 2018-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_samples', '0008_auto_20180803_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksamples',
            name='github_or_url',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worksamples',
            name='github_or_url_title',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
