# Generated by Django 2.0.5 on 2018-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('category1', models.CharField(max_length=200)),
                ('category2', models.CharField(max_length=200)),
                ('category3', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='certifications')),
                ('image_alt', models.CharField(max_length=200)),
                ('url_proof', models.CharField(max_length=200)),
                ('Summary', models.CharField(max_length=200)),
            ],
        ),
    ]
