# Generated by Django 2.0.5 on 2018-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hundred_days', '0002_auto_20180815_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='hproject',
            name='source',
            field=models.CharField(default='GitHub', max_length=50),
            preserve_default=False,
        ),
    ]
