# Generated by Django 2.0.5 on 2018-07-05 03:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2018, 7, 5, 3, 38, 41, 804536)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(),
        ),
    ]
