# Generated by Django 2.0.5 on 2018-07-05 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180705_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 7, 5, 3, 38, 59, 712020)),
        ),
    ]
